### ISSUE TITLE
Will you update?

### ISSUE THREAD

**Issue by eshimischi** [wonderful-panda/inazuma#1]
Hi, will you update this project?

**Comment by wonderful-panda** [comment]
Yes, maybe this weekend.

**Comment by eshimischi** [comment]
You have your own vision, so this project is very useful, as like a boilerplate with all your libraries. Why did you remove Pug in one of examples? @wonderful-panda

**Comment by wonderful-panda** [comment]
> Why did you remove Pug in one of examples?

Because explaining how to use pug is not a purpose of the example.
