### ISSUE TITLE
React instead of Vue ?

### ISSUE THREAD

**Issue by eshimischi** [wonderful-panda/inazuma#16]
Hi! Just curious about why did you decide to rewrite everything with React instead of Vue? And yes i saw you put efforts to add Rust backend, interesting as well. Arigatō!

**Comment by wonderful-panda** [comment]
This is my toy project and technically decisions are always made on a whim. Perhaps I'll rewrite again with Vue 3 or svelte or anything else after several months or years.

BTW, now backend code is fully rewritten in Rust with Tauri.

**Comment by eshimischi** [comment]
Yeah, i've been following your "toy project" for some years and saw all the progress also with Rust/Tauri (it was my suggestion to watch it btw:), congratulations!
