### ISSUE TITLE
Error #1

### ISSUE THREAD

**Issue by eshimischi** [wonderful-panda/inazuma#2]
https://github.com/wonderful-panda/inazuma/blob/af07add619aa9ec8e6ad32696449ee2fb7b49bc4/src/renderer/view/main/components/detailPanel.tsx#L9

`ERROR in ./view/main/components/detailPanel.tsx
    [tsl] ERROR in i:\www\vendors2017\wonderful-panda\inazuma\src\renderer\view\main\components\detailPanel.tsx(9,28)
          TS2339: Property '$store' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<Record<never, any>>>'.`

**Comment by wonderful-panda** [comment]
related code are almost all rewritten
