### ISSUE TITLE
Error #2

### ISSUE THREAD

**Issue by eshimischi** [wonderful-panda/inazuma#3]
https://github.com/wonderful-panda/inazuma/blob/af07add619aa9ec8e6ad32696449ee2fb7b49bc4/src/renderer/view/common/components/textField.tsx#L91

` TS2322: Type '{ class: "mdc-text-field__label"; style: "white-space: nowrap;"; }' is not assignable to type 'HTMLAttributes & Pick<VNodeData, "class" | "staticClass" | "style" | "key" | "ref" | "slot" | "sc...'.
      Type '{ class: "mdc-text-field__label"; style: "white-space: nowrap;"; }' is not assignable to type 'Pick<VNodeData, "class" | "staticClass" | "style" | "key" | "ref" | "slot" | "scopedSlots">'.
        Types of property 'style' are incompatible.
          Type '"white-space: nowrap;"' is not assignable to type 'object | object[] | undefined'.`

**Comment by wonderful-panda** [comment]
related code are almost all rewritten
