### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by eshimischi** [wonderful-panda/inazuma#4]
https://github.com/wonderful-panda/inazuma/blob/af07add619aa9ec8e6ad32696449ee2fb7b49bc4/src/browser/git/refs.ts#L82

fs.exists is deprecated in Node fs module, but in fs-extra it has 2 arguments instead of 1 (path, callback)
`ERROR in ../browser/git/refs.ts
    [tsl] ERROR in i:\www\vendors2017\wonderful-panda\inazuma\src\browser\git\refs.ts(82,15)
          TS2554: Expected 2 arguments, but got 1.`

**Comment by eshimischi** [comment]
We should change `fs.exists` to `fs.existsSync`

**Comment by wonderful-panda** [comment]
related code are almost all rewritten
